apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sassational-limitado
    service: os
  name: sassational-limitado
spec:
  containers:
    - image: ubuntu
      name: sassational-ubuntu
      args:
        - sleep
        - '1800'
      resources:
        limits:
          cpu: '600m'
          memory: '128Mi'
        requests:
          cpu: '300m'
          memory: '64Mi'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
