apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sassational-emptydir
    service: webserver
  name: sassational-emptydir
spec:
  containers:
    - image: nginx
      name: sassational-nginx
      volumeMounts:
        - mountPath: /sassational
          name: volume-emptydir
      resources:
        limits:
          cpu: '1000m'
          memory: '128Mi'
        requests:
          cpu: '500m'
          memory: '64Mi'
  volumes:
    - name: volume-emptydir
      emptyDir:
        sizeLimit: '256Mi'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
