apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sassational
    service: webserver
  name: sassational
spec:
  containers:
    - image: nginx
      name: sassational-nginx
      resources: {}
    - image: busybox
      name: sassational-busybox
      args:
        - sleep
        - '600'
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
